services:
  backend:
    build:
      context: ./backend
    container_name: student-task-manager-backend
    ports:
      - "3001:3001"
    volumes:
      - backend-db-data:/data

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    container_name: student-task-manager-frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"

volumes:
  backend-db-data:
